# Generated by Django 5.0.6 on 2026-05-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercache',
            name='expires_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
